### ISSUE TITLE
api文档翻译过程中属性函数无法正常翻译的问题

### ISSUE THREAD

**Issue by robin978** [Oneflow-Inc/oneflow-api-cn#40]
api文档中属性函数 如：[oneflow.nn.Graph.name](https://oneflow.readthedocs.io/en/master/graph.html)
<img width="330" alt="截屏2022-02-16 上午10 38 19" src="https://user-images.githubusercontent.com/69283456/154186277-1971486a-72fc-4340-b547-dd2209d33e77.png">
使用 ` reset_docstr ` 函数进行翻译：
```
reset_docstr(
    oneflow.nn.Graph.name,
    r"""为该 Graph 自动生成的名称。
        """)
```

翻译结束后 `make test_cn` 运行成功

`make html_cn` 运行失败，结果如下：

<img width="727" alt="截屏2022-02-16 上午10 37 56" src="https://user-images.githubusercontent.com/69283456/154186590-3f7768d7-96c3-46e4-90de-b332e9a8d103.png">

报错：
```
TypeError: Unable to convert function return value to a Python type! The signature was
        (arg0: object, arg1: str) -> object

function is property, not a valid function.make: *** [Makefile:20: html_cn] Error 2
```

**Comment by S882li** [comment]
这个可以尝试直接使用 `oneflow.nn.Graph.name.__doc__ = r"""  """` 来进行docstring重写。

**Comment by doombeaker** [comment]
哦哦，这类报错是 C++ 代码考虑不周全，需要重写。不过改起来很容易，我找时间和你们说下吧，zhaoyang 听完后有兴趣，就可以自己改
