### ISSUE TITLE
翻译约定

### ISSUE THREAD

**Issue by rainyq69** [Oneflow-Inc/oneflow-api-cn#48]
### 记录翻译时的术语对照表，以及是否要对某个术语进行翻译
例如：
- logical tensor 译为 全局视角下的 tensor ，而 physical 译为 物理机器上的 tensor
- 像 element-wise 这样的术语是开发者必知必会的内容，无需翻译

### 规定一套标点字符的使用标准
例如：
- 哪里用 attr:`something`
- 哪里用 `something`
- 哪里用 """something"""

### 记录不同标记型语言如 markdown 、 docstring 、 reStructuredText 之间语法的异同

-----
这样一个 issue 可以避免译者自己多余的纠结，而且可以保证所有文档翻译的一致性。

**Comment by doombeaker** [comment]
这个可以思考下，看最终放在 community 仓库中。还是直接放在本仓库中，以某个 md 文件方式给他人参考。

**Comment by rainyq69** [comment]
> 这个可以思考下，看最终放在 community 仓库中。还是直接放在本仓库中，以某个 md 文件方式给他人参考。

收到，现在是个雏形，先慢慢收集一些平时翻译遇到的小问题吧。

**Comment by rainyq69** [comment]
| 推荐 | 不推荐 | 推荐理由 | 举例 |
|-----|-----|-----|-----|
| 对 xxx 做 yyy 操作| 将 xxx 进行 yyy 操作 | 通顺 | 对列表中的 tensor 做规约操作 |

**Comment by rainyq69** [comment]
现关闭此 issue，理由如下：
翻译工作量其实不大，只有三个人参与，费力做一个规范反而导致效率低。
